data:
    type: "testdata"
    train_dataset: "ITS"
    val_dataset: "O_HAZE"
    patch_size: 256
    channels: 3
    num_workers: 4
    data_dir: "/opt/data/private/SJ/LPCDiff/"
    ckpt_dir: "ckpt/O_HAZE/"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 600

training:
    batch_size: 16
    n_epochs: 500
    validation_freq: 1000

sampling:
    batch_size: 1

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    amsgrad: False
    eps: 0.00000001
    step_size: 80
    gamma: 0.8